version: '2.4'

services:
  # APP
  db:
    extends:
      file: db/docker-compose.yml
      service: db

  flyway:
    extends:
      file: flyway/docker-compose.yml
      service: flyway
    depends_on:
      db:
        condition: service_healthy

  gitea:
    extends:
      file: gitea/docker-compose.yml
      service: gitea

  app:
    extends:
      file: app/docker-compose.yml
      service: app
    depends_on:
      flyway:
        condition: service_completed_successfully
      gitea:
        condition: service_healthy

  # BACKUP
  make-backup:
    extends:
      file: backup/make/docker-compose.yml
      service: make-backup
    depends_on:
      db:
        condition: service_healthy
      gitea:
        condition: service_healthy

  restore-backup:
    extends:
      file: backup/restore/docker-compose.yml
      service: restore-backup
    depends_on:
      db:
        condition: service_healthy
      gitea:
        condition: service_healthy

volumes:
  java-discord-help-bot-volume-db:
  java-discord-help-bot-volume-db-backup:
  java-discord-help-bot-volume-gitea:
  java-discord-help-bot-volume-gitea-backup:
  java-discord-help-bot-backup-data: