CREATE USER flyway WITH PASSWORD 'flyway';
GRANT ALL PRIVILEGES ON DATABASE discord_help_bot TO flyway;

CREATE USER app WITH PASSWORD 'app';
GRANT CONNECT ON DATABASE discord_help_bot TO app;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO app;