CREATE DATABASE discord_help_bot;

CREATE USER flyway WITH PASSWORD flyway;
GRANT ALL PRIVILEGES ON DATABASE discord_help_bot TO flyway;

CREATE USER app WITH PASSWORD app;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, CONNECT, EXECUTE, USAGE ON DATABASE discord_help_bot TO app;