REVOKE ALL ON schema public FROM public;

CREATE USER flyway WITH PASSWORD 'flyway';
GRANT ALL PRIVILEGES ON DATABASE discord_help_bot TO flyway;
GRANT ALL PRIVILEGES ON SCHEMA public TO flyway;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flyway;

CREATE USER app WITH PASSWORD 'app';
GRANT CONNECT ON DATABASE discord_help_bot TO app;
GRANT USAGE ON SCHEMA public TO app;
