version: '2.4'

services:
  gitea:
    image: gitea/gitea:1.22
    volumes:
      - ./conf:/data/gitea/conf
      - ./shared:/shared
      - java-discord-help-bot-volume-gitea:/data
      - ./templates:/data/gitea/templates
#      - java-discord-help-bot-volume-gitea:/var/lib/gitea
      - java-discord-help-bot-volume-gitea:/etc/timezone:ro
      - java-discord-help-bot-volume-gitea:/etc/localtime:ro
      - java-discord-help-bot-volume-gitea-backup:/tmp
    ports:
      - 3001:3001
    environment:
      - USER_UID=1000
      - USER_GID=1000
    labels:
      - docker-volume-backup.exec-label=java-discord-help-bot
      - docker-volume-backup.archive-pre.user=git
      - docker-volume-backup.archive-pre=/bin/bash -c '/shared/make-backup.sh'
      - command-runner.group=java-discord-help-bot
      - command-runner.shell=/bin/bash -c
      - command-runner.command=/shared/restore-backup.sh
    healthcheck:
      test: curl -f localhost:3001/api/healthz || exit 1
      interval: 5s
      timeout: 5s
      retries: 100
volumes:
  java-discord-help-bot-volume-gitea:

# psql -U ${POSTGRES_USER} -f /backup/current/dump.sql postgres                                                     7