version: '2.4'

services:
  app:
    image: generaltao725/java-discord-help-bot:latest
    env_file:
      - ../.env
    volumes:
      - ./config:/config
    healthcheck:
      test: curl localhost:9015/actuator/health
      interval: 10s
      timeout: 10s
      retries: 100