name: Cancel workflows on PR close
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - closed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged != true }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const workflowIds = [
              '.github/workflows/test.yml'
            ];

            for (const workflowId of workflowIds) {
              const workflowRuns = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowId,
                per_page: 100,
                event: 'pull_request',
              });
              console.log(workflowRuns);
            
              const activeRuns = workflowRuns.data.workflow_runs.filter((workflowRun) => {
                console.log(workflowRun);
                return workflowRun.status === 'queued' || workflowRun.status === 'in_progress';
              });
            
              for (const activeRun of activeRuns) {
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: activeRun.id,
                });
              }
            }

