name: Dependabot auto-approve

on:
  workflow_run:
    workflows: [ Test ]
    types:
      - in_progress


jobs:
  dependabot:
    runs-on: ubuntu-latest
#    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v3
    - name: Approve a PR
      run: |
        echo test
        echo $(gh workflow list -a)
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
